Resolve #366
Security-Experts-Community/open-xp-rules pull request #388
Opened 2024-06-18 17:34 UTC by leitosama

2024-06-19 07:10 UTC, Keks1993 requested changes

2024-06-19 07:10 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_persist/Modify_LoginHook/rule.co
> +        and object.process.fullpath == "/usr/bin/defaults"
Я бы не стал привязываться к конкретной утилите и ее аргументам. Есть и другие, например, plutil.
Злоумышленник запросто может притащить такой файлик с собой и подменить. Обратите внимание на файловые операции

2024-06-20 06:47 UTC, leitosama commented on packages/macos_open_package/correlation_rules/mitre_attck_persist/Modify_LoginHook/rule.co
> +        and object.process.fullpath == "/usr/bin/defaults"
Да, интересно. `plutil` может переписывать эту конфигурации как и `defaults`=> надо обращать внимание на изменение файлов (оставлю также тут ссылку на [HackTricks](https://book.hacktricks.xyz/macos-hardening/macos-auto-start-locations#re-opened-applications)).
Проблема в чем, из-за чего я решил избегать изначально `write`-событий: я не очень понимаю работу macOS внутри при записи файлов через свои API. Я бы описал тут на самом деле целый ряд detect'ов:
1. Оставил бы детект с `defaults`, у него есть глобальное преимущество - можно быстро понять что все-таки добавили
2. Я правильно понимаю workflow изменений получается так: `defaults`/`plutil` обращается к `cfprefsd` и от его имени создает/модифицирует файл? Тогда получается нам надо отслеживать создание файла по локации и/или модификацию в `/var/private/...`

2024-06-20 10:09 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_persist/Modify_LoginHook/rule.co
> +        and object.process.fullpath == "/usr/bin/defaults"
Действительно складывается такая ситуация как на HackTricks:

Техника объявлена запрещенной (https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CustomLogin.html), на macOS 13 не удалось выполнить закрепление таким способом (при входе в ОС ничего не запускается, хотя сам файл модифицировать удается). На более ранних версиях - запускается.

1. Как мне кажется, детект на **defaults** дает только информацию о пути. Аналитику все равно нужно придти на машину и вытащить сам скрипт, посмотреть и оценить что происходит.
Мне, все таки, видится generic-детект на модификацию файла с низким весом, который подсветит, что что-то происходит подозрительное - аналитик, посмотри, пожалуйста.

2. Да. В ОС довольно часто встречаются такие ситуации, которые напрямую связать не получается.

2024-06-26 13:04 UTC, leitosama commented on packages/macos_open_package/correlation_rules/mitre_attck_persist/Modify_LoginHook/rule.co
> +        and object.process.fullpath == "/usr/bin/defaults"
ОК, сделаем ещё другой generic-детект на `write` событие, этот переименуем, четкой причины удалить его я не вижу.

2024-07-06 08:12 UTC, leitosama commented
Добавил правило для событий `modify` демоном `cfprefsd`

2024-07-08 06:31 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_persist/MacOS_Modify_loginwindow_plist/rule.co
> +        and action == "modify"
Здесь лучше использовать msgid  или id. "action == "modify"" встречается во многих формулах нормализации.

2024-07-08 15:21 UTC, aw350m33d approved these changes

2024-07-08 15:24 UTC, aw350m33d commented on packages/macos_open_package/correlation_rules/mitre_attck_persist/MacOS_Modify_loginwindow_plist/rule.co
> +        and action == "modify"
Думаю, что остальные условия достаточно строгие чтобы ожидать фолзов.

2024-07-08 15:24 UTC, aw350m33d approved these changes

2024-07-08 15:25 UTC, merged