Resolves OSW#2: Task-4
Security-Experts-Community/open-xp-rules pull request #391
Opened 2024-06-20 14:37 UTC by Phoevek

2024-06-20 14:42 UTC, aw350m33d commented on packages/macos_open_package/correlation_rules/mitre_attck_defense_evasion/MacOS_Plist_Unsigned_Execution/metainfo.yaml
> +        - https://github.com/Phoevek
Здесь лучше указать ссылки, которые помогут разобраться в действиях атакующего. Обычно там статьи и похожие правила из других проектов.

2024-06-20 14:45 UTC, Phoevek commented on packages/macos_open_package/correlation_rules/mitre_attck_defense_evasion/MacOS_Plist_Unsigned_Execution/metainfo.yaml
> +        - https://github.com/Phoevek
> Здесь лучше указать ссылки, которые помогут разобраться в действиях атакующего. Обычно там статьи и похожие правила из других проектов.

Миссклик, исправлю сейчас

2024-06-20 14:46 UTC, aw350m33d commented
А можешь в сообщении к PR написать `Resolves #369` чтобы связать с issue и она после влития сама закрылась?

2024-06-20 14:47 UTC, Phoevek commented on packages/macos_open_package/correlation_rules/mitre_attck_defense_evasion/MacOS_Plist_Unsigned_Execution/metainfo.yaml
> +        - https://github.com/Phoevek
> Здесь лучше указать ссылки, которые помогут разобраться в действиях атакующего. Обычно там статьи и похожие правила из других проектов.

Поправил

2024-06-20 15:20 UTC, Keks1993 requested changes
В этой задаче не все так просто. Подсказка с подписью и архитектурой файла относится к битовым маскам csflags и image_cputype. Для arm исполняемых файлов подпись файла должна быть по архитектуре ОС, "неподписанный" файл имеет CS_ADHOC подпись. x86-64 исполняемый файл подпись не обязан иметь (из за трансляции розетой2). 
Для процесса в логе csflags = 570425351 (CS_VALID | CS_ADHOC | CS_GET_TASK_ALLOW | CS_DYLD_PLATFORM | CS_SIGNED), image_cputype = 16777228 (CPU_TYPE_ARM | CPU_ARCH_ABI64).

Соответственно, маски следующие:
CS_VALID = 0x00000001
CS_ADHOC = 0x00000002
CS_GET_TASK_ALLOW = 0x00000004
CS_DYLD_PLATFORM = 0x02000000
CS_SIGNED = 0x20000000

CPU_TYPE_ARM = 0x0000000c
CPU_ARCH_ABI64 = 0x01000000

2024-06-20 15:20 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_defense_evasion/MacOS_Plist_Unsigned_Execution/rule.co
> +        and match(lower(datafield10), "*com.apple.launchd*")
здесь часть строки в переменной окружения относится к переменной "SSH_AUTH_SOCK", что по задаче не совсем верно.
Лучше привязаться к 2м события:
1. launchd запускает xpcproxy com.umbrella (это имя в поле Label в plist файле).
2. В системе запускается целевой исполняемый файл (коррелирует по переменной окружения "XPC_SERVICE_NAME=com.umbrella").

2024-06-21 14:08 UTC, Phoevek commented on packages/macos_open_package/correlation_rules/mitre_attck_defense_evasion/MacOS_Plist_Unsigned_Execution/rule.co
> +        and match(lower(datafield10), "*com.apple.launchd*")
Изначально хотел привязяаться к этим событиям, но оставил одно.
По сути в атаке два ключевых момента:
1. Происходит запуск за счет абуза launchd
2. XPC_SERVICE_NAME является также переменной окружения, и как я понял из атаки там может любая ENV, главное что бы запускаемый процесс ее задействовал правильно. 
Но думаю, что два события лучше говорят о нелегитимности чем одно

2024-06-22 09:31 UTC, Phoevek commented
Обновил условия, перепроверьте пожалуйста

2024-06-23 16:09 UTC, Keks1993 approved these changes

2024-06-24 10:53 UTC, merged