Add rule to detect execution of trojan Shlayer
Security-Experts-Community/open-xp-rules pull request #393
Opened 2024-06-23 10:15 UTC by grikos

Add rule to detect execution of trojan Shlayer that distributed as fake Adobe Flash Player

Trojan Shlayer use bash script that decode another script from one of its files:

```
#!/bin/bash
cd "$(dirname "$BASH_SOURCE")"
fileDir="$(dirname "$(pwd -P)")"
eval "$(openssl enc -base64 -d -aes-256-cbc -nosalt -pass pass:2833846567 <"$fileDir"/Resources/enc)"
```

 To detect the execution of this script, we can check the execution of the `dirname` utility 
 and the subsequent execution of `openssl` with certain parameters.
 The actual password may differ in different versions of the Trojan, 
 but other parameters always remain the same.
 Including `subject.process.name` and `object.process.cwd` in the list of keys 
 are important becase we need to avoid possible false positives.
 In case of execution from such bash script (as shown above) `subject.process.name` and `object.process.cwd` must be equal.
 
 
 Resolves #376

2024-06-23 15:33 UTC, Keks1993 requested changes
Все хорошо, но хочется более обобщенное правило увидеть. Давайте уберем dirname и сосредоточимся на различных комбинациях подозрительного использования openssl

2024-06-24 07:08 UTC, grikos commented
@Keks1993 Спасибо за фидбек. 
Я допускаю, что различных комбинаций подозрительного использования openssl действительно может быть достаточное количество.
Тем не менее, считаю, что в данном случае гораздо полезнее иметь более точное правило, которое учитывает не только подозрительный вызов openssl, но и вызов dirname перед этим.
Учет последовательности этих двух событий и определенный набор параметров при запуске openssl позволяет рассчитывать на большую точность правила и меньшее число возможных ложных срабатываний на обычный запуск утилиты openssl.
Предлагаю оставить текущее правило как есть, а при необходимости разработать дополнительное правило, предназначенное для более выявления "подозрительного использования openssl" в широком смысле. Особенно с учетом того, что для полноценного исследования различных вариантов подозрительного использования openssl необходимо больше тестовых данных.

2024-06-24 08:04 UTC, Keks1993 reviewed
В целом соглашусь, но есть замечания далее по коду.

2024-06-24 08:04 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and regex(object.process.cmdline, "openssl enc -base64 -d -aes-256-cbc -nosalt -pass pass:\S+", 0) != null
В этом cmdline аргументы base64 и aes-256-cbc позиционо-независимы, могут идти в любом порядке. Кроме того, множество вариаций использования AES как по длине ключа, так и по режиму шифрования. Малейшее изменение атакующими и правило перестанет работать. В то же время, аргументы nosalt и pass не столь важны с точки зрения детекта, но тоже могут повлиять на потерю детекта в будущем.

2024-06-24 08:04 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and subject.process.name == 'bash'
Здесь могут быть различные оболочки sh, zsh, ksh, tcsh, dash, tclsh

2024-06-24 08:04 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and subject.process.name == 'bash'
Здесь могут быть различные оболочки sh, zsh, ksh, tcsh, dash, tclsh

2024-06-24 08:16 UTC, grikos commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and regex(object.process.cmdline, "openssl enc -base64 -d -aes-256-cbc -nosalt -pass pass:\S+", 0) != null
В тех вариантах трояна, которые описаны в исследованиях, использовался одинаковый набор параметров openssl.
Отличия в образцах наблюдались только в значении используемого пароля. 
Может быть существуют и другие версии подобного трояна, но в предоставленных тестовых данных нет примеров  событий, связанных с их работой. Считаю пока нецелесообразным дорабатывать логику в этом месте без возможности протестировать её на примерах.
Само по себе использование каждого из этих параметров не является признаком вредоносного поведения. 
Единственным приемлемым способом выявить признаки использования именно этой версии ВПО может служить только точное совпадение параметров командной строки с точностью до различий в пароле.

2024-06-24 08:16 UTC, grikos commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and subject.process.name == 'bash'
Нет, не могут. В первой строке скрипта, который является существенной частью трояна явно указан путь к интерпретатору:
`#!/bin/bash`

2024-06-24 08:17 UTC, grikos commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and subject.process.name == 'bash'
Нет, не могут. В первой строке скрипта, который является существенной частью трояна явно указан путь к интерпретатору:
#!/bin/bash

2024-06-24 08:40 UTC, Keks1993 commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and regex(object.process.cmdline, "openssl enc -base64 -d -aes-256-cbc -nosalt -pass pass:\S+", 0) != null
К примеру, в этой статье указаны различные оболочки (zsh, bash) и очередность аргументов base64 и aes.

2024-06-24 09:19 UTC, grikos commented on packages/macos_open_package/correlation_rules/mitre_attck_execution/Trojan_Downloader_OSX_Shlayer/rule.co
> +        and subject.process.name == 'bash'
Если не привязываться к атрибутам в представленных событиях, то тогда вообще не стоит писать правило.
Потенциальный вред от ложных сработок будет гораздо больше, чем возможная польза от такого правила.
Я не пытался написать "общее" правило для выявления подозрительно использования openssl. Изучив приложенные события я понял, что на их основе можно попробовать написать правило для выявления конкретного семейства ВПО - OSX/Shlayer.
Предполагалось, что в этом задании нужно было написать правило, выявляющее подозрительное использование openssl без привязки к конкретному экземпляру ВПО?
Если так, то нужно больше примеров событий аудита, зафиксированных во время работы различных видов ВПО, использующих openssl "подозрительным" образом. Без этого разработать правило крайне затруднительно.
На текущий момент я считаю, что разумно оставить правило без доработок, а в будущем, если действительно возникнет такая необходимость, доработать его или разработать более "широкое" правило после изучения особенностей того, как очередные атакующие начнут каким-то характерным образом использовать утилиту openssl (или какие-то другие утилиты).

2024-06-24 10:28 UTC, Keks1993 approved these changes

2024-06-24 10:53 UTC, merged