Resolves #379
Security-Experts-Community/open-xp-rules pull request #409
Opened 2024-07-01 01:56 UTC by Psych0S0cial

Разработано правило для обнаружения закрепления в системе через launchagent

2024-07-01 05:14 UTC, Keks1993 requested changes

2024-07-01 05:14 UTC, Keks1993 commented on packages/OSW_2_Task_14/correlation_rules/rule_new/rule.co
> +        and regex(lower(object.process.cmdline), "launchctl.*?\/users\/user\/library\/launchagents\/com\.apple\..*?\.plist", 0) != null
"launchctl.*?\/users\/user\/library
user - имя локального пользователя, оно может быть любым

2024-07-01 06:36 UTC, Psych0S0cial commented
Обновил regex, совсем забыл про имя пользователя...

2024-07-01 06:58 UTC, Keks1993 approved these changes

2024-07-01 16:32 UTC, aw350m33d commented
Привет!

А ты бы мог файлы офрмить единообразно с другими правилами в репозитории?
Вот как пример: https://github.com/Security-Experts-Community/open-xp-rules/pull/400/files#diff-ce4e24d522d45d47edeab3cb300870ddb07c79c43ebdd34ae17cdad5123de2dd

На что обратить внимание:
1) структура папок. У нас уже сложилась определённая структура, попробуй синхронизировать свой форк с базовым репозиторием, затем обновить master и влить его в свою ветку с правилом. Потом просто нужно будет перенести правило в папку для подходящей тактики.
2) файл метаинформации не заполнен. если нажать правой кнопкой на правило и выбрать "Метаинформация", то откроется окошко для заполнения необходимых данных

2024-07-08 14:19 UTC, aw350m33d approved these changes

2024-07-08 14:19 UTC, merged