Создано правило корреляциии которое реагирует на запуск файлов из скр…
Security-Experts-Community/open-xp-rules pull request #410
Opened 2024-07-01 16:40 UTC by Protenil

Правило корреляции срабатывает при запуске процесса из скрытой аудитории. Логика основана на соответсвии типа события (action = execute) и наличия в поле object.process.cmdline сочетания символов "/.", что соответствует скрытому каталогу.
Resolves #370

2024-07-02 07:49 UTC, Keks1993 requested changes

2024-07-02 07:49 UTC, Keks1993 commented on packages/system/normalization_formulas/MacOS/es-logger/open_sec/rule.co
> +        and find_substr(object.process.cmdline, "/.") != Null
С таким условием на путь будут ложные сработки. К примеру, dir1/../f, т.е. запуск из родительского каталога.

2024-07-02 08:46 UTC, aw350m33d commented on packages/system/normalization_formulas/MacOS/es-logger/open_sec/rule.co
> +        and find_substr(object.process.cmdline, "/.") != Null
Наверное, лучше использовать регулярные выражения вместо поиска подстроки.

2024-07-08 17:12 UTC, aw350m33d commented on packages/system/normalization_formulas/MacOS/es-logger/open_sec/rule.co
Регулярное выражение поправил, посмотри, если интересно. Плюс перенёс правило в нужную папку.

2024-07-08 17:12 UTC, aw350m33d approved these changes

2024-07-08 17:13 UTC, merged